spring.application.name=SpringBootApplicationExample

spring.datasource.url=jdbc:postgresql://localhost:5432/oris-spring-2026-2
spring.datasource.username=postgres
spring.datasource.password=qwerty
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.hello-message=Hello world from ITIS!